import { UserProvider } from "@/context/user";
import "./globals.css";
import Header from "@/components/header/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  console.log("RootLayout initialized");
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Header />
          {children}
        </UserProvider>

      </body>
    </html>
  );
}
